# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Test Score Guide OR # &#58; is ":" (cannot have colon in title)

sitename: "Oregon’s Assessment of Knowledge and Skills Test Score Guide"
statename: "State of Oregon"


email: someone@somewhere.org
description: > # this means to ignore newlines until "baseurl:"
  This Web page serves as a gateway to information and resources parents/guardians can use to understand OAKS Smarter Balanced Assessment Student Score Reports.

# baseurl: ""                      # local devlopment path
# baseurl: "/ca-tsg-new/_site"     # dev path
# baseurl: "/ca"                   # production path
#
# do NOT forget to uncomment the google analytics
# before publishing this site to the production enviroment
#
baseurl: "/ca-tsg-new/_site"     # dev path
url: "http://testscoreguide.org" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

kramdown:
   input: GFM
